name: latex

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/latex.yaml
      - '**.tex'
      - latexmk
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2


      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex \
                                  texlive-fonts-recommended \
                                  texlive-latex-recommended \
                                  texlive-latex-extra \
                                  texlive-fonts-extra \
                                  texlive-bibtex-extra \
                                  texlive-biblatex

      - name: List fonts (optional debug)
        run: fc-list | grep -i roboto || true

      - name: Compile with lualatex directly
        run: |
          lualatex -interaction=nonstopmode -halt-on-error resume.tex
        
      # - name: Compile LaTeX document
      #   uses: xu-cheng/latex-action@3.2.0
      #   with:
      #     root_file: resume.tex
      #     latexmk_use_lualatex: true
      #     extra_fonts: |
      #       ./fonts/FontAwesome.ttf
      #       ./fonts/Roboto-Bold.ttf
      #       ./fonts/Roboto-BoldItalic.ttf
      #       ./fonts/Roboto-Italic.ttf
      #       ./fonts/Roboto-Light.ttf
      #       ./fonts/Roboto-LightItalic.ttf
      #       ./fonts/Roboto-Medium.ttf
      #       ./fonts/Roboto-MediumItalic.ttf
      #       ./fonts/Roboto-Regular.ttf
      #       ./fonts/Roboto-Thin.ttf
      #       ./fonts/Roboto-ThinItalic.ttf

        env:
          TEXINPUTS: ".//:"
            
      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: resume.pdf
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload resume.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: resume.pdf
